### PR TITLE
SnPM 13.1.06 including #25 and #26

### PR DESCRIPTION
**Pull request by cmaumet**
This PR includes the following updates that will be part of SnPM 13.1.06 release:

 - fix: "all equal" and "all zero" options were flipped in ANOVA between-group (6dbc714).
 - fix: 	fix: 'Error using ==. Matrix dimensions must agree' when locations are in a 1D space (36ca029).

### CODE REVIEW

**Comment by cmaumet** [comment]
@nicholst: I have run the tests and they still pass (without any update) which is not what I was expecting given that the "all equal"/"all zero" option is now reversed. 

Looking at the test data in [here](https://drive.google.com/drive/folders/0ByYytkxqR-v0RW1JT0loWmJpODA?usp=sharing), the two following test cases:
 - Between-group ANOVA "all equal" (other options to default) - cf. [results](https://drive.google.com/drive/folders/0ByYytkxqR-v0Q3ZBbVZVbjRWME0?usp=sharing) 
 - Between-group ANOVA "all zero" (other options to default) - cf. [results](https://drive.google.com/drive/folders/0ByYytkxqR-v0OWVYb2hyekl0ejQ?usp=sharing)

seem to produce the same results.

I am unsure whether this is a flaw in the design of the test case of if there is a bug somewhere. 

The `CONT` variables look fine:
```
>> allequal=load('GT_SnPM8_2014b/ANOVAbetween_1/SnPMcfg.mat')
>> allzero=load('GT_SnPM8_2014b/ANOVAbetween_allzero/SnPMcfg.mat')
>> allequal.CONT

ans =

     1     0    -1
     0     1    -1

>> allzero.CONT

ans =

     1     0     0
     0     1     0
     0     0     1
```

Can we have a look together this afternoon to check if everything is fine?

**Comment by cmaumet** [comment]
@nicholst: Sorry about the confusion! I have just double-checked and the output *are* different (I was initially comparing the beta maps which are indeed equal but the F-stat maps are different). And because the "all zero"/"all equal" option were already properly set in the test script, tests are not impacted by 6dbc714. So, it is normal for the tests to pass even though the option order has changed.

Let's check if we can include #7 in this release as well and then I will upload the new update online.

**Comment by nicholst** [comment]
@cmaumet - Yes this sounds like a plan.  #7 should definately be included, but let's also see what problem the most recent comment is about... at first blush I don't know why the user is still having memory problems.

**Comment by cmaumet** [comment]
Test report for SPM12, Matlab R2014b:
```
Totals:
   70 Passed, 0 Failed, 0 Incomplete.
   464.7302 seconds testing time.
```

**Comment by cmaumet** [comment]
Test report for SPM8, Matlab R2014b:
```
Totals:
   70 Passed, 0 Failed, 0 Incomplete.
   445.4265 seconds testing time.
```

**Comment by cmaumet** [comment]
SnPM 13.0.6 is now available on the SnPM website: www.warwick.ac.uk/snpm/snpmreg.

**Pull request merged**
